server:
  port: 9095

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/profile_db
    username: root
    password: Hiten@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
  application:
    name: profile-service


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

